### ISSUE TITLE
Insecure credential storage

### ISSUE THREAD

**Issue by altf4** [MediaBrowser/Emby#1074]
Emby user passwords are insecurely stored using an unsalted SHA1 hash, processed client-side.

**Unsalted passwords**
When password hashes are stored in a backend database, they must be salted in order to prevent against precomputation attacks. Salts ensure that every user's password hash is unique. Without salts, attackers who gain access to password hashes (via eavesdropping on the network or by compromising the database) will be able to reverse the hash into the original password very easily.

Salts must be generated using a cryptographically secure random number generator, and appended to the plaintext password before hashing. Note that if you choose to use  a hashing algorithm like bcrypt (see below) salting is already taken care of for you.

See:
Password Salt
http://en.wikipedia.org/wiki/Salt_%28cryptography%29

Rainbow Tables
http://en.wikipedia.org/wiki/Rainbow_table

**SHA1**
The SHA1 algorithm is unsuitable for password storage. SHA1 is a hashing algorithm designed to be processed as quickly as possible. This is a trait that only helps attackers as they attempt to crack password hashes. 

Instead of SHA1, use a modern password hashing algorithm which has been specifically designed for the needs of password storage such as bcrypt, scrypt, or PDKDF2. 

SHA1 Attacks
http://en.wikipedia.org/wiki/SHA-1#Attacks

Google Security Blog: Deprecation of SHA1
http://googleonlinesecurity.blogspot.com/2014/09/gradually-sunsetting-sha-1.html

**Client-side processing**
The standard model for providing credentials from client to server is for the client to send the password in plaintext to the server. The server then securely hashes this password and stores only the hash in a backend database for later retrieval. For security against eavesdropping, an HTTPS (or other encrypted connection as necessary) connection is required. 

Emby, however, hashes the user's password on the client side. (In JavaScript, for the web interface) This password is then stored directly into the backend database as is. This represents a security vulnerability.

An attacker who compromises the database no longer needs to crack any passwords at all. This defeats the entire purpose of hashing passwords at all. The password hashes themselves have become the effective password itself. If ever a user's password hash is compromised in any way, an attacker can hijack the user's account by replaying the password hash back to the server. 

Remove the client side hashing functionality, submit passwords in plaintext to the server, and securely hash and salt passwords before storing.

Thanks!

**Comment by ebr11** [comment]
Since https cannot be used in all situations, sending passwords in plain text is not advisable.

All of the information you provided above is technically correct, but it must be balanced with the actual vulnerability and need.  We are securing access to media content that is stored already within a (most likely) insecure file system.  If one were to gain access to the physical Emby database, they have gained access to that file system and, therefore, any passwords for our system are irrelevant at that point.

Also, most of the clients do not store any form of a password on their end (hashed or otherwise).  Instead they store an access token that can be readily revoked at the server end requiring the client to re-authenticate.

Security is important to us and we have made improvements in this area and will continue to do so.  However, there are many practical factors to take into account when doing so.

**Comment by xmob** [comment]
But by sending a password hash and comparing it to the hash in the database, you *are* sending passwords in plain text.

How things are at the moment is the same as sending the password and plaintext *and* storing the passwords in the database as plaintext.

**Comment by jabbera** [comment]
no matter what, without universal ssl support through the Emby ecosystem this is going to be a problem. Everyone recognizes that and is working towards a better solution.

**Comment by LukePulverenti** [comment]
I think this ticket makes some good points, and if https were mandatory this is how we would have proceeded in the first place. So really the question is how do we approach this given that https is optional. Or if we choose to make https mandatory, how do we do that so that average Joe user doesn't even have to know about it. That's really the key, otherwise it's just going to cause a lot of pain.

**Comment by jabbera** [comment]
HTTP 2.0 supports alt services which will basically be DSL without certificate validation. 

In the short term we would need to provide a way to overide cert validation errors on each platform unless end users want to purchase ssl certs or use the free eff platform when it comes out.

**Comment by altf4** [comment]
Good comments! For sure, the only way to ensure confidentiality when submitting user credentials is an end-to-end encrypted channel. No amount of client side hashing can solve that problem. HTTPS being mandatory would be a great step forward for security. Though that can be considered separately from the question of how to store credentials in the backend.

@jabbera One option to consider for for certificate validation on thick clients is certificate pinning. The idea is that rather than using the Certificate Authorities built into the platform, you create an Emby CA, hardcode its public key into the thick clients (Android app, Roku app, etc...), then have the client validate against that CA. It effectively bypasses the main weakness in HTTPS: The certificate authorities. It's more secure (because you're only trusting one CA and not the whole list of foreign governments in the default CA list) and more convenient.

What this would let you do is provide (perhaps just to paid subscriber people. Monetization opportunity!) an Emby supplied HTTPS certificate that their thick client apps will just recognize and be cool with. No need to (perhaps unsafely) ignore SSL errors. The only area where this doesn't work is in the browser. There is no thick app to hardcode a cert into. But perhaps manually accepting a funny SSL cert one time in the browser is worth it "just working" on all the other platforms.

Certificate Pinning
https://www.owasp.org/index.php/Certificate_and_Public_Key_Pinning

Thanks!

**Comment by altf4** [comment]
@ebr11 You are correct that HTTPS is really necessary for a secure transport of credentials to the server. But supposing that this is impossible for some reason, it is still a security vulnerability to send client-hashed passwords as Emby currently does. 

It feels strange, I know. But consider every major website on the Internet. Until relatively recently, sites like Google, Facebook, and Twitter had HTTP as the default, and an optional HTTPS site. (Similar to Emby's current configuration) And what they did was send plaintext passwords via HTTP, and hash them on the backend. That is the most secure option.

**Comment by jabbera** [comment]
They never sent password via plaintext. The login pages have always been ssl.

**Comment by altf4** [comment]
Not true. The EFF's HTTPS-Everywhere project was created specifically because of the problem of major websites having HTTP as default. In each of these cases, user credentials were being sent in plaintext over HTTP, before the switch.

HTTPS-Everywhere
https://www.eff.org/HTTPS-EVERYWHERE

2011: Twitter announces option to use HTTPS by default
https://blog.twitter.com/2011/making-twitter-more-secure-https

2013: Facebook switches to HTTPS default
https://www.facebook.com/notes/facebook-engineering/secure-browsing-by-default/10151590414803920

2010: Gmail switches to HTTPS default
http://gmailblog.blogspot.com/2010/01/default-https-access-for-gmail.html
(They had a user option for it, previously)

**Comment by jabbera** [comment]
All of those references are about encrypting all traffic to and from those
websites. The login pages have always been encrypted.

Sent from my iPhone.

On Apr 12, 2015, at 3:43 PM, AltF4 <notifications@github.com> wrote:

Not true. The EFF's HTTPS-Everywhere project was created specifically
because of the problem of major websites having HTTP as default. In each of
these cases, user credentials were being sent in plaintext over HTTP,
before the switch.

HTTPS-Everywhere
https://www.eff.org/HTTPS-EVERYWHERE

2011: Twitter announces option to use HTTPS by default
https://blog.twitter.com/2011/making-twitter-more-secure-https

2013: Facebook switches to HTTPS default
https://www.facebook.com/notes/facebook-engineering/secure-browsing-by-default/10151590414803920

2010: Gmail switches to HTTPS default
http://gmailblog.blogspot.com/2010/01/default-https-access-for-gmail.html
(They had a user option for it, previously)

—
Reply to this email directly or view it on GitHub
<https://github.com/MediaBrowser/MediaBrowser/issues/1074#issuecomment-92107065>
.

**Comment by ebr11** [comment]
Since we are open-source, any hard-coded key or certificate in that source is readily obtainable.

**Comment by altf4** [comment]
Good question. It is a hardcoded public key, as in asymmetric cryptography. So it is not a secret. The reason you hardcode it in the app is to have a secure way of distributing it, in the same way that every other CA certificate is distributed in the browser. 

Public Key Cryptography
http://en.wikipedia.org/wiki/Public-key_cryptography

**Comment by jabbera** [comment]
The public and private key are a pair. How would suggest we keep the private key a secret since we are open source and don't host the server software? If it's not secret we might as well use http as anyone can decrypt the traffic. 

Also, we can override certificate validation errors on roku or windows 8.1 store apps. (There may be other platforms that don't let you do this as well) 

Pinning only prevent MITM attacks by spoofed certs from bad cert authorities.

**Comment by altf4** [comment]
Just to recap: The certificate pinning thing is just a suggestion for a possible way to handle HTTPS for thick client apps. It's really separate from the question of how to store credentials once the server has received them. If you would like, I could make a separate github issue to implement (and discuss) certificate pinning. 

To answer your questions, I am not familiar with the Emby backend infrastructure so it's hard for me to say definitively what's possible, but it does not require anything major. Pinning is something that is really common for app developers, and a good security measure. But it can definitely be described as a "nice-to-have".

TLS certificates come in two halves: private and public. The public certificate is the thing that the server sends out to clients in order to prove who it is. This certificate is not a secret and is the thing that you look at when you view the certificate for the current website you're at. For example, here is Github's public TLS cert:

![selection_234](https://cloud.githubusercontent.com/assets/609563/7121282/5b8bae8e-e1c8-11e4-81b5-edd454cf3ad1.png)

The web browser knows to trust this certificate because it has been issued by DigiCert, which is a certificate authority built into the browser. The certificate authority system is the main weakness in HTTPS, since any certificate authority is capable of creating a valid certificate for **any** website, thus being able to spy on it. There has been lots of precedent for CAs being compromised by hackers or otherwise coerced by local governments, so this is a real issue.

Certificate pinning solves this problem by creating your own certificate authority, and telling your app "Trust only this CA, and no others". This drastically reduces your surface area for risk in HTTPS. There are no TLS error to ignore, since clients will be given a valid certificate signed by an authority they trust.

So you would in fact need to keep the Emby CA private key a secret, but only in the same way that any other site (including every other open source project) keeps their TLS keys secret. I noticed there is an HTTPS site: https://connect.mediabrowser.tv/ It would be no different than that.

I hope that helps.

**Comment by jabbera** [comment]
Hosting a CA as you are suggesting has nothing to do with certificate pinning. Certificate pinning is just telling your browser (or application) what the public key\certificate for your well known website is. This way, if a bad CA which was in your trust chain did issue a cert for a pinned website, the browser or application could tell you. (See the following: https://www.owasp.org/index.php/Pinning_Cheat_Sheet) In other words, pinning basically prevents a MITM attack even if someone has obtained a cert for a website illicitly that would otherwise be valid in your trust chain.

All of that said issuing an emby CA root cert with the private key well known to all and allowing users to generate ssl certs from it isn't a bad idea if we were able to override the certificate validation process on all platforms as we would NEVER want the cert in the OS or browser trust chain. I'm not sure if this is possible but will do some digging on it.

**Comment by telyn** [comment]
you could automatically generated the private key on startup. However I personally feel like this is over-engineering it. I agree with @altf4 - the current setup is equivalent to storing passwords in plaintext on the database. Storing passwords salted and hashed is all Emby really needs to do in my opinion.

For over-the-internet situations, let it be up to the person installing Emby to provide the SSL certificate and keys for their hostname. What I myself do is place Emby behind nginx and use nginx for SSL termination, but I admit that I haven't investigated how my Chromecast connects to it in that case.

**Comment by LukePulverenti** [comment]
The storage is changing, as well as the api. We will use bcrypt. For now we will have to leave this behind a hidden config switch while we give clients a sizable grace period to adapt (at least 6 months). Enabling it will result in only being able to login with apps that have been updated. Thanks.
