### ISSUE TITLE
Ubuntu Packaging

### ISSUE THREAD

**Issue by gyger** [MediaBrowser/Emby#1116]
Hello,
Ubuntu 14.04 uses no official mono builds, only packages from the repository that was provided by emby. This is not really an advisable strategy, because all my mono packages are removed that are used by other software.

**Comment by LukePulverenti** [comment]
What would you suggest? You could try the docker release. Every other team is doing the same, take a look at Sonarr. We try and keep our repo as a mirror of Xamarin which is the default mono builder. Granted we have fallen a little behind and need to update current version on official mono repos is 4.0.2.5-0xamarin1. That being said, since ours is a mirror it shouldn't be an issue to update to the newest official release. How do you define official? Our sources are direct copies of xamarin and same with the packaging files. The only thing we do is change the name of the tgz source file and the changelog in order expedite the packaging process.
