### ISSUE TITLE
Authenticate users using LDAP

### ISSUE THREAD

**Issue by mcladyz** [MediaBrowser/Emby#1146]
Do you LDAP authentication support planned? Thanks for the great software.

**Comment by LukePulverenti** [comment]
I wouldn't rule it out. A few people have mentioned it, but overall we probably need to see a little more demand for it before investing the time.

**Comment by Larx** [comment]
I'd vote for LDAP, too.

**Comment by sdfg2** [comment]
Me too :-)

**Comment by Cadair** [comment]
+1

**Comment by cdancette** [comment]
+1

**Comment by abeudin** [comment]
+1

**Comment by Aidenir** [comment]
+1

**Comment by joshuaboniface** [comment]
I too am extremely interested in this feature! I see a forum post marking it "DONE" on December 12th; any idea when it will make it to release?

**Comment by LukePulverenti** [comment]
Nothing has been done for this.

**Comment by jstruebel** [comment]
+1 from me on this. Is it possible to do this through a plugin or will it need changes to the core server?

**Comment by quentinus95** [comment]
+1

**Comment by MarinBernard** [comment]
+1

**Comment by mbantegui** [comment]
+1 on this, would love to have this feature.

**Comment by PoGo606** [comment]
+1 Can't wait for it !

**Comment by spdy** [comment]
+1

**Comment by mescribe0** [comment]
+1

**Comment by williamkray** [comment]
ugh, i'm sorry to do this, but +1 as well. github really needs a way to star an issue or something to indicate affected users, etc.

**Comment by markopolo123** [comment]
I'd also love to see this.

**Comment by Half-Shot** [comment]
+1 I wonder what's involved in writing a plugin or something.

**Comment by untotren** [comment]
+1

**Comment by ben-kuhn** [comment]
+1

**Comment by michaelwfullerton** [comment]
Me too. Would be great to see this feature

**Comment by quentinus95** [comment]
Any news on this ? It seems that there is "a little more demand" :smiley:

**Comment by karbowiak** [comment]
+1

**Comment by jalgroy** [comment]
+1

**Comment by quentinus95** [comment]
@LukePulverenti Can you give a feedback about this potential feature ?

**Comment by LukePulverenti** [comment]
We have interest but there are some prerequisites that are required before it can be looked at. We have to restructure our authentication into a more modular system. That in turn has a prerequisite which is SSL working out of the box for all users without any advanced configuration. We currently don't have that right now. The self-signed certs are a pain and require additional configuration with client apps, and on some platforms that's not even possible. So that's what we need to figure out first.

**Comment by jooola** [comment]
+1

**Comment by Dark-Feather** [comment]
My network is also very interested in this -- we use LDAP for all other authentication elements except media access.

**Comment by quentinus95** [comment]
Any news on when #2139 will be merged ?

**Comment by SeanHood** [comment]
+1

**Comment by LayfonWeller** [comment]
+1

**Comment by jorgensoares** [comment]
+1

**Comment by SuperManitu** [comment]
+1

**Comment by zelogik** [comment]
Normally I never ask for new feature, but here... I feel the need...

+1

**Comment by Luticus** [comment]
I'm converting all web authentication on my personal site to LDAP.

This would be extremely useful for me.  Definitely +1!

**Comment by Larx** [comment]
Any official statement ;-) ? I follow this issue and feel kinda spammed by +1 comments.

**Comment by PoGo606** [comment]
@LukePulverenti Could you give us an update on this matter ? That would be nice !

**Comment by mathieu-mp** [comment]
+1 !

**Comment by Coac** [comment]
+1

**Comment by thex1ade** [comment]
+1

**Comment by Larx** [comment]
Is it still worth following this thread, and any hope that LDAP will get implemented? Everything in here is lots of "+1", but no response :-(.

**Comment by PoGo606** [comment]
Well, is someone has a more "direct" way to the developpers and ask them ?

Also, how about this pull request ? [2139l](https://github.com/MediaBrowser/Emby/pull/2139l) 
@jose-pr have you got any feedback from @LukePulverenti ?

**Comment by LukePulverenti** [comment]
Hi guys, we would very much like to do this. We are currently focused on Live TV and offline syncing, but after those things get to where we want them then we can certainly take a look at this.

If someone here would like to take on some projects related to this, then please send me a message in the Emby community and I will give you some development tasks. There are things we can take from @jose-pr 's pull request, but much has changed since then and there are also a few adjustments I would like to make. I am happy to offer direct guidance if there is someone who would like to take on some of the work. Thanks.

**Comment by cgheonea** [comment]
+1 and yes, I'd like to take this project and do the integration. 

I have experience with php, sqlite, xml, json and I think I can also learn on the go .net

**Comment by Dark-Feather** [comment]
three cheers for @cgheonea !

**Comment by PoGo606** [comment]
Hooray @cgheonea \o/

**Comment by untotren** [comment]
Make sure to +1 this FR
https://emby.media/community/index.php?/topic/26495-ldap-support/

**Comment by DMWOO7** [comment]
I also support this, since LDAP seems to be the only thing missing in Emby to be part of a full stack homeserver. Where Emby is great for serving movies and music, I need additonal software like NextCloud as personal cloud. A hand of family members or friends are enough to create a mess of not-synced accounts. That's the reason I want to use ApacheDS as LDAP server, create centralized accounts for every user and manage their roles by group memberships. 

All other software I'm using like the mentioned NextCloud has LDAP support. Only Emby is missing, which is pity, since it's a great software in his job.

**Comment by untotren** [comment]
the original post with a thumbs up

Also endorse the post on the Emby site.
https://emby.media/community/index.php?/topic/26495-ldap-support/

**Comment by Guimli** [comment]
+1

**Comment by hagterof** [comment]
+1

**Comment by godfuture** [comment]
+1

**Comment by benyanke** [comment]
1+ as well. I'm looking to move most of my home server services to LDAP, to make usage of multiple apps by single users far easier.

**Comment by zippy-man** [comment]
+1 this is one of my last pieces of software that is not integrated with my AD server for centralized account management.

**Comment by untotren** [comment]
I created a centralized FR for this guys, please like the original post on the thread, it links to many requests like this one but all in one place to show how heavily this is desired. :)

https://emby.media/community/index.php?/topic/26495-ldap-support/

**Comment by jcgruenhage** [comment]
@LukePulverenti As for having TLS enabled in emby before that: I'm pretty sure a lot of people run this behind a reverse proxy handling TLS instead of emby, so forcing TLS in emby means we'll have an encrypted channel from emby to the reverse proxy, which live on the same machine in my case, which would needlessly burn CPU time.

**Comment by Dark-Feather** [comment]
I can agree with @jcgruenhage -- it would be nice to support LDAP, LDAPS, and LDAP over STARTTLS, all of which are flags to the LDAP binaries.

**Comment by jhayet** [comment]
+1

**Comment by softworkz** [comment]
There's news in the forum post, please read: https://emby.media/community/index.php?/topic/26495-centralized-authentication-functionality-ldapssohtml-headerradius/page-8

**Comment by LukePulverenti** [comment]
If you'd like to participate in testing, please see here: https://emby.media/community/index.php?/topic/56793-ldap-plugin

Thanks guys.

**Comment by Dark-Feather** [comment]
I'll see if I can't give it a shot

**Comment by LukePulverenti** [comment]
Great, thanks. I added a screenshot so that you can see the settings that are available in the plugin setup screen.

**Comment by Dark-Feather** [comment]
May  take me a bit. I have what is supposed to be the arch beta branch from the user repo installed, and I don't see the plug-in. I have a sneaking suspicion that the package isn't actually pulling the beta branch

**Comment by mueslo** [comment]
I installed 3.3.1.2-beta from the Github releases and the same thing happens for me. Can't see any new plugins.

**Comment by LukePulverenti** [comment]
Try it now, you should be able to find it. It's in the General section. Thanks.

**Comment by Dark-Feather** [comment]
I can in fact find it -- having a little trouble with my localhost API address complaining but I should be able to finish testing logins tonight.

**Comment by LukePulverenti** [comment]
The beta looks to be going well. You can now configure default user permissions for newly imported LDAP users, and the change password function is now supported as well.

https://emby.media/community/index.php?/topic/56793-ldap-plugin/

Enjoy.

**Comment by LukePulverenti** [comment]
I'm closing this now as we have the basics covered in the beta server and LDAP plugin.

I'm happy to look at new improvements for this. Please open new topics for the changes you'd like to see, either here or in our user community. Thanks !

**Comment by benyanke** [comment]
Also, for those looking to test, glauth is a great lightweight LDAP server. I have a docker image here as well: benyanke/glauth:latest
