### ISSUE TITLE
Episode naming conventions (02 Ep. Name)

### ISSUE THREAD

**Issue by ineentho** [MediaBrowser/Emby#1282]
Your wiki page on [TV Naming](https://github.com/MediaBrowser/Wiki/wiki/TV-naming#episode-naming-conventions) says that `02 Episode Name.avi` is a valid naming scheme. However it's not supported:

Successfully identified:
```
TV Shows\Silicon Valley\Season 1\02 - The Cap Table.avi
TV Shows\Silicon Valley\Season 1\02. The Cap Table.avi
```

Not working:
```
TV Shows\Silicon Valley\Season 1\02 The Cap Table.avi
```

Is the software or the wiki that's wrong?

**Comment by LukePulverenti** [comment]
Well we have passing unit tests with those kinds of names so it really depends on what you mean by not recognized.

https://github.com/MediaBrowser/Emby.Naming/blob/master/MediaBrowser.Naming.Tests/TV/EpisodeNumberWithoutSeasonTests.cs

Recognized simply means episode and season number are parsed out of the name. Or maybe they are recognized and there's some problem in some later stage with downloading metadata.

**Comment by ineentho** [comment]
Look again. You only have `ep. Name.ext` and `ep - Name.ext`, not `ep Name`
in there.

I actually even downloaded Emby.Naming through nuget and verified my
claims, but I didn't wanna  mess with the quite complex rexexes so I didn't
try to create a PR.

**Comment by LukePulverenti** [comment]
Yes you are correct. We have adopted kodi naming standards and after going over the supported formats and the unit tests, I believe this is by design. Without a separator between the episode number and episode title, it is difficult to handle the situation where the episode title is a numeric value or starts with a numeric value. That's why all of the supported conventions either use a separator, or use a prefix on the numbers, for example, S01E01.

**Comment by ineentho** [comment]
Sure, seems fine to me. I still suggest that you update the wiki to reflect that, since that's where to confusion stem from. https://github.com/MediaBrowser/Wiki/wiki/TV-naming#episode-naming-conventions
