### ISSUE TITLE
[Suggestion]  Ogg Vorbis 

### ISSUE THREAD

**Issue by tap3** [MediaBrowser/Emby#1290]
Hi,

Is more a suggestion that a issue :
I was searching for how to change the transcoding parameters [ffmpeg]
But I read that you could not change them.

So why not change the transcoding FLAC> MP3 to FLAC> OGG

Why?
Because Ogg is free and open-source : mp3 isn't
Ogg vorbis quality of the mp3 are supperior ...

---
another french guy who need learn english :)

**Comment by LukePulverenti** [comment]
Hi, welcome. I don't have anything against this but we don't have that option right now because nobody has really cared about it up until now. 

Truthfully with projects like flac js, we probably won't need to transcode flac much longer anyway so that's probably where we're going to put our efforts.

**Comment by tap3** [comment]
Ok Thx for the answer :+1: 

Is this feature available in the delevop repository ?

**Comment by LukePulverenti** [comment]
Not yet but it's something I'd like to look at.

**Comment by LukePulverenti** [comment]
Until we have in-browser flac decoding, we will switch to opus for browsers that support that, which is higher quality than what we're using now.
