### ISSUE TITLE
Could we have some off line installers?

### ISSUE THREAD

**Issue by StephenR0** [MediaBrowser/Emby#1387]
Your web site is down and I have no way to install the server or Media Browser Classic. Do we have to rely on your web server? What about some mirrors?

**Comment by karbowiak** [comment]
Could be an idea to not use Linode, and switch to someone else - and also start using Cloudflare for all exposed http/https services, maybe? ^^

**Comment by RedshirtMB** [comment]
Karbowiak.

Linode isn't a tiny operation. Abandoning ship just because of one outage, even though it was a big one, seems a bit knee jerk. 

I for one am in a way glad the outage happened. It lets the devs assess how the emby ecosystem handles a large scale outage and determine what changes should be made across the server, clients and web services.

**Comment by LukePulverenti** [comment]
If you check out the releases you can click into one and download assets for that release:
https://github.com/MediaBrowser/Emby/releases

So while we're not going to rework our installer what we can do is document a portable install method that involves grabbing the assets directly from github.

As for Linode, I'm sure going forward they are going to have dramatically improved DDOS protection, so we're not really going to make any judgments until this is over.

**Comment by StephenR0** [comment]
I'm sure documenting a portable install method would be just fine.  Thank you for finding a solution.
