### ISSUE TITLE
Identifier not relevant

### ISSUE THREAD

**Issue by noraj1337** [MediaBrowser/Emby#1722]
Hi,

the automatic identifier is totaly chaothic : 
my game of thrones episode s06e03 (imdb tt4131606)
is identified to
Batman: The Animated Series.

In the identifier search page if I put title = **game of thrones**\+ imdb id = **tt4131606** (episode id) is find the good episode presentation, so I don't understand how it could be possible to first obtain Batman.

Other example, a sample of tv show is identified to [Shomin Sample](http://www.syominsample-anime.jp/) anime only because there is **sample** in the name of the file ...

**Comment by LukePulverenti** [comment]
It's not even possible to use the identify feature for episodes. We don't expose it because all you need to do is make sure the series folder is identified, then ensure the episode has season and episode numbers. Did you follow the tv naming guide?

https://github.com/MediaBrowser/Wiki/wiki/TV%20naming

**Comment by shark-oxi** [comment]
I read the naming page before to post here but I thought that identifier could work without changing name of files because I don't want to rename my file. (torrent seeding, so renaming = changing the unique hash + I don't to soo).

**Comment by LukePulverenti** [comment]
This should no longer be an issue. If it is, please re-open. thanks !
