### ISSUE TITLE
[Feature Request] Different languages for metadata and images

### ISSUE THREAD

**Issue by horstepipe** [MediaBrowser/Emby#1820]
would be very helpful if you could set the languages for metadata and images/fan arts separately.

**Comment by LukePulverenti** [comment]
FYI it is better to create feature request topics in our community because that allows us to gauge interest levels from other users. Without that feedback some of these may end up sitting here in an open state forever. Thanks.

**Comment by horstepipe** [comment]
these were the requests which stayed unanswered in the community so I hoped to get some attention here

**Comment by stormwatch** [comment]
+1

On a more general note I think that what is needed is the capability to store and search metadata in more than one language. At least 1) the original language of the release, 2) the language defined in the locale, and 3) other languages selected arbitrarily. More often than not, I would like to use the original title rather than the local spanish translation, eg. “Julie Darling” rather than the awful «Déjala Morir Adentro». Sometimes I'd rather stick to a literal translation of the original title: “Ein Mann geht durch die Wand” was released in english as "The Man Who Walked Through The Wall" which seems acceptable. The original spanish release on the other hand was titled «Apenas un Duende» which translates into english as "Just a Pixie" :P

**Comment by LukePulverenti** [comment]
Ability to set a preferred image language independent of metadata will be in Emby Server 4.2. Thanks.
