### ISSUE TITLE
"H.264 bitstream malformed, no startcode found" via Chrome / HLS

### ISSUE THREAD

**Issue by Lafticgohed** [MediaBrowser/Emby#2391]
#### This error is from playback with Chromium and Google Chrome browsers and probably any others that rely on HLS.
[small sample of the video which experiences the same issue](https://a.pomf.cat/nfleoz.mp4)
- Playbackof the file is fine via the android emby application.
- Playback of the file is fine via mpv / vlc.
<br>

In my configuration I have enabled 
> Allow audio playback that requires transcoding

if this is disabled the problem is "fixed" as this video's audio is AAC however I have lots more videos with AC-3 audio which I would prefer be transcoded so that Chromium can play it.

<br><br>
### The error:

Ffmpeg/mpegts fails to make ts's for some files,
>H.264 bitstream malformed, no startcode found, use the video bitstream filter 'h264_mp4toannexb' to fix it ('-bsf:v h264_mp4toannexb' option with ffmpeg)
[Full emby log](http://pastebin.com/raw/8bfV2hDH)

if you try emby's ffmpeg command manually but also add the flag <b>-bsf:v h264_mp4toannexb</b> ffmpeg outputs a playlist.m3u8 and the ts's as expected initially

[mediainfo for original video](http://pastebin.com/raw/mtKMTGvH)

Hopefully this is just a configuration error.

**Comment by LukePulverenti** [comment]
The file is missing all media info. We have some decision making that decides whether or not to use the bitstream filter based on media info.

What this means is either - you just setup the library and the scan hasn't completed yet, or there was a problem probing the file for media info and that's why it is empty. Try refreshing the metadata from the detail screen using the 3-dot menu. then see if that fills in more information at the bottom of the detail screen.
