### ISSUE TITLE
APPX based WSA for installation on Windows Server nano?

### ISSUE THREAD

**Issue by andlo** [MediaBrowser/Emby#2393]
I was looking for a way to install Emby on a Windows Server nano. But for that it has to be made as an APPX. Anyone who has looked into this - any experianse in this?

https://blogs.technet.microsoft.com/nanoserver/2015/11/18/installing-windows-server-apps-on-nano-server/

**Comment by LukePulverenti** [comment]
Can't you just grab the portable download?

**Comment by LukePulverenti** [comment]
It appears Nano is obsolete now, therefore we won't be moving forward with it: https://www.petri.com/nano-server-today-gone-pretty-soon

However, we will commit to Windows Server Core, and Emby Server already runs on that, although there is some setup required: https://github.com/MediaBrowser/Emby/issues/2924

In a future update to the server we will resolve that so that the setup step is not required. Thanks !
