### ISSUE TITLE
Error while shutting down Emby via Systemd

### ISSUE THREAD

**Issue by xoxys** [MediaBrowser/Emby#2595]
OS: Debian 8.7 
Mono: Mono JIT compiler version 4.6.2
Emby: 3.2.13.0

Hi,
i have updated my Emby Server to the latest stable version. If i try to stop emby service via 
`systemctl stop emby-server` i get following error

```
Apr 24 13:36:18 HOST systemd[1]: Started Emby Media Server.
Apr 24 13:36:19 HOST su[2036]: Successful su for emby by root
Apr 24 13:36:19 HOST su[2036]: + ??? root:emby
Apr 24 13:36:19 HOST su[2036]: pam_unix(su:session): session opened for user emby by (uid=0)
Apr 24 13:37:00 HOST systemd[1]: Stopping Emby Media Server...
Apr 24 13:37:00 HOST systemd[1]: emby-server.service: main process exited, code=exited, status=197/n/a
Apr 24 13:37:00 HOST systemd[1]: Stopped Emby Media Server.
Apr 24 13:37:00 HOST systemd[1]: Unit emby-server.service entered failed state.
```

After this emby is still running:
```# ps -aux | grep emby
emby      2057  0.0  0.1  35648  3748 ?        Ss   13:36   0:00 /lib/systemd/systemd --user
emby      2059  0.0  0.1  90116  2252 ?        S    13:36   0:00 (sd-pam)  
emby      2061  4.7 15.3 948120 316260 ?       Ssl  13:36   0:43 /usr/bin/mono-sgen --optimize=all /usr/lib/emby-server/bin/MediaBrowser.Server.Mono.exe -programdata /var/lib/emby-server -restartpath /usr/lib/emby-server/restart.sh
```

After killing all emby processes a can restart emby successfully. Emby was installed via official repository
`http://download.opensuse.org/repositories/home:/emby/Debian_8.0`

Thanks for your work.
Regards Robert

**Comment by LukePulverenti** [comment]
What if you just shutdown from the web interface? How does that compare?

**Comment by xoxys** [comment]
Shutting down via webinterface is working like a charm.

**Comment by LukePulverenti** [comment]
Closing with won't fix - won't fix with the current mono version that is. We are currently reworking Emby Server to run with the smaller and faster Microsoft .NET Core runtime. You can participate in testing here:
https://emby.media/community/index.php?/topic/50012-emby-server-for-net-core/

So far we are not seeing any issues with shutdown, however if something does come up with this version then we'll look into it. In the near future our current set of Linux packages will be switched to run with .NET Core instead of Mono. Thanks !
