### ISSUE TITLE
[feature request] .nfo handling

### ISSUE THREAD

**Issue by DARKFiB3R** [MediaBrowser/Emby#2727]
I have recently discovered that emby has overwritten hundreds of my scene release .nfo files.

These files, while incompatible with emby, or any other software of it's kind, still contain much valuable information.

Please give users a very prominent warning that their files will be overwritten if they choose the nfo saving option.

Further, if emby were to rename any existing nfo files, (perhaps by appending the file name with [emby]) before creating it's own, this would solve the issue.

**Comment by LukePulverenti** [comment]
I am closing this with wontfix but that doesn't mean it can't happen, it just means it won't happen in the core emby server. We can't rename our nfo's to emby because that goes against one of our major goals -
 to use a metadata format that many other applications support. What you should do is disable saving to nfo. Saving via alternative methods can then happen via a community plugin. Thanks !
