### ISSUE TITLE
Login disclaimer does not show html contents anymore (3.2.26.0-49.1)

### ISSUE THREAD

**Issue by fbartels** [MediaBrowser/Emby#2805]
Hi,

for quite a while I have used the login disclaimer field to show some additional information on the emby login page. for this I have added some html code in the field to have a clickable link.

I have recently noticed that instead of the clickable link, it currently shows the html syntax instead.

Was that changed on purpose or is this a possible xss hardeling side effect?

**Comment by LukePulverenti** [comment]
Yes this is by design. Since the feature is used by the store apps, allowing custom content places us at risk of violating app store policies. Additionally it is also used by our online web app, app.emby.media, and seeing that on the login screen can lead one to believe that there is some affiliation with Emby, which is obviously not the case. Thanks.

**Comment by fbartels** [comment]
Hmm. ok fair enough. Then I have to find a different place to put these links.

**Comment by mrmuiz** [comment]
2025 Time to put this back in? Only a text as disclaimer doesnt get read so well and doesnt look so good.
