### ISSUE TITLE
[BUG] Advanced Hosting options not taking effect when saving

### ISSUE THREAD

**Issue by karbowiak** [MediaBrowser/Emby#2830]
Hi there!

Bug is pretty simple, you put in the settings you want to use, and scroll to the bottom and tick off "Report https as external address", hit save and get

```To enable reporting https as your external address, you will need to supply a trusted SSL certificate, such as Lets Encrypt.```
After which you hit "Got it" and nothing happens - it doesn't save.

Leave that off tho, and it works.

**Comment by LukePulverenti** [comment]
Did you enter a custom cert? Perhaps the message needs to be re-worded, but we are no longer allowing you to enable https as the external address unless you supply a custom cert.

**Comment by karbowiak** [comment]
Oh that explains it then.

I wasn't adding a custom cert since it's running behind caddy. But technically Emby is available at the https address, so it could show it supports https no?

(Not that it matters too much, i redirect anything from port 80 to 443 anyway)

**Comment by LukePulverenti** [comment]
It makes sense, it's just that Emby doesn't have any way knowing that it's behind something else that is handling ssl. So we'd have to have a way to make you confirm that.

**Comment by LukePulverenti** [comment]
Being able to report as https in your situation would still be nice to avoid all of those redirects.

I guess that leaves two options - you either enter a cert into Emby, which won't actually be used since Caddy is handling it. But entering it will make the config screen happy so that you can check that box.

Or, we could have another box you can check to indicate that Emby is running behind another web server which handles the ssl certificate. When that box is checked, the config screen would allow you to proceed.

**Comment by LukePulverenti** [comment]
Ok, for now guidelines would be that if you are behind a proxy then you should leave it off and let the proxy handle it. Thanks.
