### ISSUE TITLE
No player for some movies

### ISSUE THREAD

**Issue by Earl0fPudding** [MediaBrowser/Emby#2859]
When I am in the web interface for emby and I want to see a movie the player doesn't show up, also the bars with a fanart of the movie don't go away and there is a loading circle that spinns and won't go away. When this happens I am not able to change the video quality or audio track for example.

I found a solution for this problem: On the page where you can manage the libraries, you have to scan the library where your movie is for new metadata and then it should work fine.
But if you want to watch the movie again, you have to do all this again.

What's the cause of this problem? Is this a bug?

I am using emby Version 3.2.30.0 on a debian 9.1 server.
The screenshot beneath shows the occurring problem.
![Screenshot](https://abload.de/img/bildschirmfotovom2017xdpc1.png)

**Comment by LukePulverenti** [comment]
Please attach the information requested here: https://emby.media/community/index.php?/topic/739-how-to-report-a-problem/

Thanks !

**Comment by LukePulverenti** [comment]
The problem is we have no media info for your file. Perhaps this failed during the initial library scan due to an ffprobe error. Try refreshing the file manually from the web app detail screen, then see if this fills in missing information such as the runtime. Once you have that, then try to play again.

**Comment by Earl0fPudding** [comment]
Thank you very much!
I refreshed the metadata and it works now.
