### ISSUE TITLE
Feature: Possibility to force transcoding audio

### ISSUE THREAD

**Issue by Richard87** [MediaBrowser/Emby#2980]
I have a chromecast with a crappy TV that only support an extremely limited selection of audio codecs, so I wish to force transcoding the audio when stream to chromecast

**Comment by LukePulverenti** [comment]
What audio codec are you having a problem with?

**Comment by brianjmurrell** [comment]
Similar problems with files that have only AC-3 in them but devices (looking at you Apple) that can't play/downmix audio locally.

**Comment by LukePulverenti** [comment]
The apple tv example is not valid here because we already detect that and convert the audio as needed. If you're finding this isn't happening then please see how to report a media playback issue:
https://emby.media/community/index.php?/topic/739-how-to-report-a-problem/
Thanks.

**Comment by LukePulverenti** [comment]
Closing due to abandonment. @Richard87 please feel free to re-open if you are able to provide the requested information. Thanks !

**Comment by brianjmurrell** [comment]
Just looking at this from a different angle, so was:

> The apple tv example is not valid here

in response to my:

> files that have only AC-3 in them but devices (looking at you Apple)

?  If so, I was not looking at Apple for their TV but for their iPad and iPhone which also have limited codec support and could use (audio-only) transcoding.  But this is also going to be true for Chrome/Android devices that can't downmix AC-3 also.

In fact, other than advanced media playing software like Mplayer, VLC, etc. is *anything* capable of downmixing AC-3 to something more usable?

It seems like there is a whole class of situations where a downmix/audio-only-transcode from an AC-3-only audio file is needed.

**Comment by LukePulverenti** [comment]
@brianjmurrell, In the case of Chromecast, the Chromecast device tells us what codecs are supported, however, I believe I have heard of cases where this detection is incorrect and could possibly lead to sending audio to the TV that it doesn't support. If we're truly not able to detect this, then the only solution is a setting.

In the case of Apple TV and iOS, we can detect when AC3 is supported and I've not heard of any cases where this detection is inaccurate. Therefore, if you're asking for a setting as a means to resolve a problem, I'd rather just look at whatever problem you're having so that we can make it work out of the box. If it turns out that this isn't possible, then a setting would be valid, but I would like to get to the bottom of that first. Thanks.

**Comment by LukePulverenti** [comment]
In other words what I'm saying is that for android, iOS and Apple TV, any required downmixing should already be happening out of the box.

**Comment by brianjmurrell** [comment]
Subject to the _Allow audio playback that requires transcoding_ setting in a user's profile though?

I read that as the setting that says "allow transcoding of audio (but not video)".

Has that always been there or was it introduced just recently?

**Comment by LukePulverenti** [comment]
Those settings have been there for a long time. A use case for those settings would be running the server on a device that doesn't have any horsepower for transcoding, so you use the server switch to deny transcoding altogether. In this situation the app will do it's best to direct play the file, subject to the supported media formats for the app.

**Comment by brianjmurrell** [comment]
So, I recall seeing those transcoding settings and have set them because indeed, my Emby server does not have the horsepower to transcode video in real time.

What I don't remember seeing before was specifically the _Allow audio playback that requires transcoding_.  Is that describing what I am interpreting it as?  That it will transcode the audio of an A/V media file if necessary?  Or is that only applicable to audio-only files like music?

**Comment by LukePulverenti** [comment]
It is a setting to allow it, and applies to both music and audio within video files. Keep in mind the help text below. It is not guaranteed that all media will be playable in every app if you take away access to transcoding.

**Comment by brianjmurrell** [comment]
> It is not guaranteed that all media will be playable in every app if you take away access to transcoding.

Understood.  For the case of just needing to transcode/downmix audio, the server should be able to handle that and should be allowed so that the media item is playable.  For video, the server just cannot handle it so regardless, the user just cannot watch the media on the device they are trying to.

**Comment by brianjmurrell** [comment]
In any case, I will adjust user account settings and see if this resolves my problem of videos with only AC-3 being unplayable on certain devices.

**Comment by brianjmurrell** [comment]
I am still having problems with audio on chromecast devices.

Given a media file that has just an AC-3 track, it plays on my Android phone but I have only gotten it to play once (out of many attempts) on my chromecast connected directly to my 2-speaker television.  Other than that once, I get video only and no audio.
