### ISSUE TITLE
Number of photos

### ISSUE THREAD

**Issue by Mikohaza** [MediaBrowser/Emby#2999]
Dear all,

If the number of photos in the folder exceeds 500 - 510, the first photo in the folder will open even if the preview is correct.
This in every case, via browser, dlna.
Is there any limit?

best regards,
Istvan

**Comment by Mikohaza** [comment]
Unfortunately, it still does not work.
best regards,
Istvan

**Comment by linusgirdland** [comment]
Bump!

Please fix this issue soon. Cannot be that difficult to look into and find the cause. I've experienced this bug for so long now, and I finally found this posting confirming that it is a known bug.

It is a very annoying bug. I do not want to completely re-organize my photo collection folders in order to work around the bug and view photos through Emby as all photos have been indexed already in various photo apps I use. Having to re-organize the folder would void all my indexes, tags etc in my photo collection.

**Comment by rofrantz** [comment]
Indeed my issue from https://github.com/MediaBrowser/Emby/issues/3003 was closed but tge issue is still present :(

**Comment by Mikohaza** [comment]
No fix yet :(

**Comment by Mikohaza** [comment]
No fix yet :(

**Comment by linussweden** [comment]
Finally fixed!

Looks like its working now. Tested in web UI (in chrome), android phone, ios ipad, emby theater windows desktop.
I could not be happier. :)

/Linus
