### ISSUE TITLE
IDependencyContainer alternative?

### ISSUE THREAD

**Issue by Randomage** [MediaBrowser/Emby#3087]
Hi,

I've been playing around with a metadata plugin and I was using IDependencyContainer which has been removed in the latest beta version - is there another way I can register my dependencies so Emby will inject them into my plugin?

Thanks!

**Comment by LukePulverenti** [comment]
Hi, I removed this because it's not actually used in the core server and I generally don't like keeping code around that isn't used. I am open to a more modular container system where both the server and plugins could use the same thing.

But until we have that I would suggest defining objects in your plugin class, and assuming you've setup a static singleton like most other plugins, you can then access those objects that way. If you have any objects that need disposal, you can have the plugin implement IDisposable and handle it there.

I realize this isn't the dependency injection you're asking for, but it does at least give you some kind of life cycle management. Thanks.

**Comment by Randomage** [comment]
That's cool, I can work with that. Thanks for explaining!
