### ISSUE TITLE
Chromecast still active when disconnect from Emby iOS app

### ISSUE THREAD

**Issue by MatYRicS** [MediaBrowser/Emby#3131]
I don't know if this is the right place to post this issue. But I have just switched from Plex to Emby yesterday and was testing everything. I noticed that when I have played a movie and want to disconnect Emby from the Chromecast and close the Emby iOS app. Then the Chromecast is still active in Emby on my TV from the Chromecast and also if I look in the Server Dashboard under Active Devices it is still there as Active even tho I clicked disconnect in the iOS app.

**Comment by 10481** [comment]
I've had this happen as well. Someone will let the movie run all the way through and the device (phone or tablet) will disconnect over time but the chromecast will remain on (connected) in the emby dashboard indefinitely until the chromecast is reset. The buttons for stopping playback dissappear presumably because playback has stopped, yet it's impossible to remove the device from the active position. Ultimately, I think it ends up taking a spot from the available devices queue, but I'm not positive.

**Comment by LukePulverenti** [comment]
This is resolved for the next release of the app, thanks.
