### ISSUE TITLE
Request for Enhancement (RFE) - Ability to block IPs by country from access to Emby.

### ISSUE THREAD

**Issue by Lord-Malgus** [MediaBrowser/Emby#3135]
This is a request to add the ability to block users by country (IP address).  Having this ability built-in to Emby would be a nice bonus.   I would love the to have the option to block any IP outside the USA as an extra level of protection.  I realize this could be down via software or certain router firmwares, however having this integrated in Emby would be an extra boon.

**Comment by LukePulverenti** [comment]
Hi, that's not easy to do. It would be much easier to instead whitelist the ip addresses that you consider to be friendly.

**Comment by Lord-Malgus** [comment]
I'm currently using Windows Firewall to accomplish what I want.  However having the ability to Tell Emby to only allow USA addresses for example would be a nice option..   If that is outside the scope of Emby, please go ahead and close out this request.

**Comment by LukePulverenti** [comment]
The ability to associate an IP with a country is not always easy, especially when taking VPN's into consideration. That's why I think it would be out of our scope because i see a lot of troubleshooting in our future such as "X ip address was detected as the wrong country". The amount of time we would end up spending on that I think would just pull us away from media management which is where our focus is. A whitelist on the other hand is something we can easily do. Thanks.
