### ISSUE TITLE
[Feature Request] Find Item by External ID

### ISSUE THREAD

**Issue by whvneo** [MediaBrowser/Emby#3216]
When using "/Search/Hints?searchTerm=xxx" it would be nice to enter also an external ID in order to find the correct movie/tv.

It could be also "/Search/ExternalIdInfo/TheMovieDB/68721" in order to get the movie with this ExternalIdInfo to TheMovieDB.

With this feature it is possible to check if a movie in a list in "themoviedb" is already available in the local emby library.

kind regards
Andreas

**Comment by LukePulverenti** [comment]
Well, we won't add this to the search api because starting with 3.5 you can use the regular items querying api and simply include a SearchTerm param. Going forward that should be how you search.

@softworkz  dev note - In ItemsService, come up with a way to expose query.AnyProviderIdEquals with the api.

**Comment by LukePulverenti** [comment]
This will be in Emby Server 3.6. Check out the AnyProviderIdEquals param in swagger. Thanks.
