### ISSUE TITLE
debian/ubuntu repository outdated

### ISSUE THREAD

**Issue by ggzengel** [MediaBrowser/Emby#3307]
I always update my systems with apt-dater without to login to the system.
Since 3.4 emby shows new updates but I don't get it.

To download and install it manually is like building cars before tin lizzie.

**Comment by paddatrapper** [comment]
I'm having the same issue....

**Comment by LukePulverenti** [comment]
If you're running our legacy install package, then right now a manual update will be required. The steps listed to do so are in posts #3 and #4 here:
https://emby.media/community/index.php?/topic/58613-question-about-my-32-bit-upgrade/?p=574032
Thanks.

**Comment by paddatrapper** [comment]
That is not the issue... I'm running at 64 bit Debian stable install. The issue is that the OpenSUSE repo only contains version 3.3.1. Why is this no longer being updated? 

Updating using the deb provided on your website works fine, but I don't want to have to wget a deb for every update, which is why the repo worked very well in the past with unattended upgrades enabled

**Comment by LukePulverenti** [comment]
Right now there are some compatibility problems with the older OpenSuse installations that are making this difficult. We will probably later setup a brand new repository for our newer packages, but we don't have one at the moment.

**Comment by LukePulverenti** [comment]
We're not going to be using the opensuse repositories anymore, but we most likely will set up new ones in the future.

Please feel free to leave feedback here:
https://github.com/MediaBrowser/Emby/issues/3283

Thanks !
