### ISSUE TITLE
[Feature Request] Parallise Library Updates

### ISSUE THREAD

**Issue by jaketame** [MediaBrowser/Emby#3333]
I'm not sure if its currently a feature but judging by the log it seems to be updating movies on a per item basis.

Can we;

- Create a array of new files
- Create 1-10 workers
- Split array of new files to workers
- Pull down metadata / art etc into the workers

Cheers

**Comment by softworkz** [comment]
There may be opportunities for parallelization, but specifically downloading metadata is something that we must not do in parallel. Not even 2 simultaneous workers.

This is due to the fact that web servers are often limiting simultaneous requests, often just to just 2.
Other metadata services have mechanisms to detect excessive downloading which may result in being blocked. For some metadata services, emby has it's own API key, so the worst case could be that a metadata provider would block emby as a whole for all users.

A while ago we already had conversations with metadata providers about the load that emby is causing and we've worked together with another one to change its API in a way that emby can download series data with a single query instead of making single requests for each episode. So that's a real concern.

That's why the described method is not really suitable here.

Parallelization is still a good idea, but it would need to be done in a different way.
We must not parallelise by item but by operation instead. Like one worker scanning the file system, one worker identifying unknown items, one worker downloading metadata from PoividerA, one worker for ProviderB, another worker for downloading images etc.

**Comment by jaketame** [comment]
Sorry for late response, crazy busy with a new job...

This completely makes sense... Because Emby is open-source.. What are the options for allowing users to provide API keys to said metadata services? Either free tier / paid tier ? We could then allow more third-party metadata sites for indexing?

**Comment by softworkz** [comment]
There's just a handful of "good" metadata sites, adding more does not help here in general.
But metadata providers can be added as plugins now. So, for some special interest areas or coverage of a certain country or language, it might make sense to create a plugin to add a specific provider.

Also it wouldn't help to allow specifying a custom API key because most of those sites will limit requests to 1 or 2 parallel ones by **origin** - **not** by API key. If you were thinking that these 2 simultaneous requests would be shared among all emby servers, then you got me wrong. This is not the case.

**Comment by LukePulverenti** [comment]
The newly released Emby Server 4.0 will feature faster library scans. Thanks.

**Comment by LukePulverenti** [comment]
You can expect significantly faster library scans in the upcoming 4.8 server release. Thanks.
