### ISSUE TITLE
Emby Crashes while playing Music

### ISSUE THREAD

**Issue by zsmbrvr** [MediaBrowser/Emby#3441]
I can replicate this every time I play music from my library. 
Currently running version 3.5.3.0 on Ubuntu 16.04. 
Logs: https://pastebin.com/p2fr04kF

Issues seems to be similar / identical to #3391
The only difference I see is that here I have

> (Memory`1 buffer)

 and in 3391 it is 

> (Memory1 buffer)

**Comment by LukePulverenti** [comment]
Hi there, can you attach the complete emby server log? thanks !

**Comment by zsmbrvr** [comment]
Hi,
It seems that it crashes only when I open up an album and try to play something.
It also crashed when I selected "Albums" from the top of the music library.
https://pastebin.com/jG11npR3

**Comment by LukePulverenti** [comment]
This is due to the defect that was in 3.5 and 3.5.1. It is actually a .net core runtime defect and as a result we've disabled the audiodb provider until .net core 2.1.5 is released with the fix.

However, your music library still has audiodb image urls saved and the server is still attempting to download them, thus causing the crash. Your only fix right now is to remove your music library from emby, run a library scan after removing it, and then you can add the music library back. thanks.

**Comment by LukePulverenti** [comment]
Please let us know if there is still an issue. Thanks.

**Comment by zsmbrvr** [comment]
Sorry, I forgot to reply.  It is not longer an issue.
This fixed it:

>  Your only fix right now is to remove your music library from emby, run a library scan after removing it, and then you can add the music library back. thanks.
