### ISSUE TITLE
Beta source code missing

### ISSUE THREAD

**Issue by nvllsvm** [MediaBrowser/Emby#3479]
There are 3.6.*.* releases available on both [Docker Hub](https://hub.docker.com/r/emby/embyserver/tags/) and the [Emby site](https://emby.media/linux-server.html). Where is the source code?

**Comment by LukePulverenti** [comment]
It's not available at this time, sorry.

**Comment by nvllsvm** [comment]
Will the stable release be available under the GPLv2?

**Comment by LukePulverenti** [comment]
No, if you check out our recent announcement, we now have additions that are costing us money. We cannot open source that. Instead we are modularizing and open sourcing as many standalone components as we possibly can.

**Comment by nvllsvm** [comment]
Context: https://emby.media/exciting-additions-coming-soon-in-emby-server-36.html

So the core will be proprietary, but some additions will be open source?

**Comment by nvllsvm** [comment]
Thanks for the prompt response and clarifying this.

**Comment by aconitumnapellus** [comment]
Thank you for clarifying. Made my decision to move to another opensource software much faster!

**Comment by softworkz** [comment]
[Disclaimer: The following is a private opinion, not an official statement]

It always makes me smile when I see people stomping their foot on the ground and shouting "let's do a fork!".

I'm laughing about this because those shouts are always coming from persons that are obviously expecting that they just need to perform a fork and then there's some magic going to happen: The "open source community" - where everybody works for free based on altruistic motivations - would immediately step up and start working and continue development on the project - without any kind of compensation of course...
That's just a sad dream though, which will never come true. Even a single person working full time wouldn't be sufficient. You would need a team working day and night for no income to keep up with it.
From that perspective it doesn't matter which version of source code you can get. Even if Emby would publish the complete source code at its current state - in less than a year it would be so outdated (no bugs fixed, no user issues addressed, no requested features implemented), that nobody would want to continue using it much longer and people would stand begging for the recent source code again.

The commercial aspects must not be seen as a payment for the code and the completed work at a current state. A current state could be given away for free at any time. But nobody would be happy with that for a longer period, when no more work would be done on it, no problems solved, no bugs fixed, no forum questions answered, no features added.

Think you can find a team of volunteers that are doing all this - full time?
I don't!

But if somebody wants to fork: Yes please, don't talk, don't announce - just do it! The publicly released code is public. Forever. Take it. Work on it! Start developing! Make it better! Show your skills and compassion! Create pull requests for the public plugins. Maybe there's even room for collaboration at some time.

Besides that, I'm really wondering if there could be even a single reason for Emby to release the full source code to a community where the majority of recent efforts was about bypassing paid feature requirements. 

[End of private statement]

**Comment by aconitumnapellus** [comment]
> [Disclaimer: The following is a private opinion, not an official statement]
> 
> It always makes me smile when I see people stomping their foot on the ground and shouting "let's do a fork!".
> 
> I'm laughing about this because those shouts are always coming from persons that are obviously expecting that they just need to perform a fork and then there's some magic going to happen: The "open source community" - where everybody works for free based on altruistic motivations - would immediately step up and start working and continue development on the project - without any kind of compensation of course...
> 
> That's just a sad dream though, which will never come true. Even a single person working full time wouldn't be sufficient. You would need a team working day and night for no income to keep up with it.
> 
> From that perspective it doesn't matter which version of source code you can get. Even if Emby would publish the complete source code at its current state - in less than a year it would be so outdated (no bugs fixed, no user issues addressed, no requested features implemented), that nobody would want to continue using it much longer and people would stand begging for the recent source code again.
> 
> The commercial aspects must not be seen as a payment for the code and the completed work at a current state. A current state could be given away for free at any time. But nobody would be happy with that for a longer period, when no more work would be done on it, no problems solved, no bugs fixed, no forum questions answered, no features added.
> 
> Think you can find a team of volunteers that are doing all this - full time?
> I don't!
> 
> But if somebody wants to fork: Yes please, don't talk, don't announce - just do it! The publicly released code is public. Forever. Take it. Work on it! Start developing! Make it better! Show your skills and compassion! Create pull requests for the public plugins. Maybe there's even room for collaboration at some time.
> 
> Besides that, I'm really wondering if there could be even a single reason for Emby to release the full source code to a community where the majority of recent efforts was about bypassing paid feature requirements.
> 
> [End of private statement]

You mean the paid features which were introduced without notice as for example the beautiful "nag" screen every few seconds?
Im not for bypassing paid features, im paying for emby premiere. Since years.
And i see this as a complete f*ck up over me. Im really angry over this change.

**Comment by softworkz** [comment]
> You mean the paid features which were introduced without notice as for example the beautiful "nag" screen every few seconds?
> Im not for bypassing paid features, im paying for emby premiere. Since years.
> And i see this as a complete f*ck up over me. Im really angry over this change.

I'm very sorry about your bad experience. You should not see any nag screen as a paid member (I think not even as a non-premiere member).

What's your user name on the emby forums? I will follow up via PM.

**Comment by softworkz** [comment]
Or just send a PM to @softworkz

**Comment by ergo** [comment]
Hm, are there any examples of other projects that do it this way? What is the point of open sourcing anything at all if the base/core is closed?

**Comment by softworkz** [comment]
I agree - we will need to improve both stability and documentation of the plugin API.

Typically, "Plugin API" sounds like made for some nice-but-not-needed stuff. But meanwhile it has evolved to an anchor point for modularization of functionality and this will allow us to keep as much code open source as possible and invite anybody to collaborate.

**Comment by kitten77** [comment]
I have a "lifetime" key for your software, and if this is the way you choose to do this. It won't be renewed, i bought it when this was a open source project. And back then there was no mentioning about closing the source or even close, so for me this is a deal breaker. This is not the first time you left me feeling like a jackass for supporting your development, thanks alot guys

**Comment by softworkz** [comment]
@kitten77

> I have a "lifetime" key for your software, and if this is the way you choose to do this. It won't be renewed

You are funny. You say you won't renew your lifetime(!) license..? How would that go?

Are you related with @aconitumnapellus ?
It's the same kind of humor:

> You mean the paid features which were introduced without notice as for example the beautiful "nag" screen every few seconds?
> Im not for bypassing paid features, im paying for emby premiere. Since years.

aconitumnapellus has been paying Emby premiere for years, although he is seeing nag screens every few seconds. 
Wow, that's a faithful customer :-)

> Thank you for clarifying. Made my decision to move to another opensource software much faster!

A customer so satisfied that he's paying for years. And now - all of a sudden....

Come on guys, who do you think will believe this play you're acting here...?

**Comment by kitten77** [comment]
@softworkz well in the Emby world a lifetime isn't really a lifetime subscription.

**Comment by ahoythedinghy** [comment]
> [Disclaimer: The following is a private opinion, not an official statement]
> 
> It always makes me smile when I see people stomping their foot on the ground and shouting "let's do a fork!".
> 
> I'm laughing about this because those shouts are always coming from persons that are obviously expecting that they just need to perform a fork and then there's some magic going to happen: The "open source community" - where everybody works for free based on altruistic motivations - would immediately step up and start working and continue development on the project - without any kind of compensation of course...
> 

The Mate desktop environment, Trinity Desktop environment, Devuan distro, Libre Office, and many other projects might disagree about that assertion.  On what possible basis would you suggest that people can't fork a major project and be successful with it?  Those are just the ones I could easily list off the top of my head.  Could I personally fork this project and do anything of value with it?  Absolutely not, but there are certainly people who could.

If there was any possibility of not putting a bad face on this, your attitude surely isn't helping, "Private Statement" or not.  How can you be a developer on a major (formerly) Open Source project but seem to have so little respect for what the FLOSS community is capable of?

**Comment by softworkz** [comment]
Many of the projects you mentioned are backed and funded by institutions having interest in the respective projects.

BTW: How do you think that `people can['t] fork a major project and be successful with it` ?
How could they be "successful" without any income?

I have great respect for any volunteer developer. I've contributed to a number of open source projects as well. 
But that level of respect decreases rapidly for people that tend to assume that it would be their very right to benefit from the work of others - not only based on others' courtesy but even otherwise.

**Comment by isubasinghe** [comment]
I agree with @kitten77 I feel cheated, I wouldn't have paid a single cent If I knew emby was going to be proprietary.

**Comment by softworkz** [comment]
> I never said im seeing nag screens right now, i said it happened one time. And i was a paying emby premium customer there.
> Im not happy with the state of emby since like a year, but i kept paying the pass.
> You know why? because i thought its gonna change for the better.
> But i guess it wont change, it gets worse.
> And as i have a yearly subscription, im strongly thinking about not renewing it, as im not satisfied as a customer.

> 
> Also do you really think i was 100% "satisfied" with emby for years? Im not.
> But that was, "the straw that breaks the camels back".
> Also this is not a play. But keep believing this you sneaky little troll.

**Comment by aconitumnapellus** [comment]
> > I never said im seeing nag screens right now, i said it happened one time. And i was a paying emby premium customer there.
> > Im not happy with the state of emby since like a year, but i kept paying the pass.
> > You know why? because i thought its gonna change for the better.
> > But i guess it wont change, it gets worse.
> > And as i have a yearly subscription, im strongly thinking about not renewing it, as im not satisfied as a customer.
> 
> > Also do you really think i was 100% "satisfied" with emby for years? Im not.
> > But that was, "the straw that breaks the camels back".
> > Also this is not a play. But keep believing this you sneaky little troll.

Bist ja ein ganz witziger Bursche

**Comment by softworkz** [comment]
> I never said im seeing nag screens right now, i said it happened one time. And i was a paying emby premium customer there.
> Im not happy with the state of emby since like a year, but i kept paying the pass.
> You know why? because i thought its gonna change for the better.
> But i guess it wont change, it gets worse.
> And as i have a yearly subscription, im strongly thinking about not renewing it, as im not satisfied as a customer.

Please tell me under which e-mail address did you register? Then we could arrange a refund.

> Also do you really think i was 100% "satisfied" with emby for years? Im not.
> But that was, "the straw that breaks the camels back".
> Also this is not a play. But keep believing this you sneaky little troll.

I'm sorry that you feel this way. Would you be able to share some details about the things that you're dissatisfied with?

**Comment by baconfeet** [comment]
"There is no such thing as a free lunch"

Paying for premium to have updates on a constant basis? Bug fixes? Support responses within 24hrs on the forums? Nothing is free, especially time/labor.

**Comment by aconitumnapellus** [comment]
> > I never said im seeing nag screens right now, i said it happened one time. And i was a paying emby premium customer there.
> > Im not happy with the state of emby since like a year, but i kept paying the pass.
> > You know why? because i thought its gonna change for the better.
> > But i guess it wont change, it gets worse.
> > And as i have a yearly subscription, im strongly thinking about not renewing it, as im not satisfied as a customer.
> 
> Please tell me under which e-mail address did you register? Then we could arrange a refund.

Im not sure if i want a refund yet. 
Maybe the team decides otherwise.
I will send you my email address with PM on the forums. I wont specify my information here, as this is my work account.

> > Also do you really think i was 100% "satisfied" with emby for years? Im not.
> > But that was, "the straw that breaks the camels back".
> > Also this is not a play. But keep believing this you sneaky little troll.
> 
> I'm sorry that you feel this way. Would you be able to share some details about the things that you're dissatisfied with?

- Emby getting closed source.
- Emby Mobile Apps are closed since years, which is really shit, because the apps have some huge issues with playback (Files not starting playing at all without any logs, app freezing when viewing items, etc) 
- Some Emby Apps for like SmartTV are not working at all, like the Trizen App (One of my friends stated that 2 months ago, maybe it changed now. The app just kept crashing)
- API Documentation and the API seems to change with every Update (Also the API documentation wasnt available at all for a long f*cking time, see swagger)
- Communication of the Emby Team, nothing more needed to be said.
- The "We release something without announcing it beforehand" which they are doing since ... idk. (Mobile Apps suddenly closed, suddenly .net core sourcecode is gone, or like now, suddenly code closed.
- Libraries are still not "available offline" after years. What that means:
Imagine your library is stored on a FUSE mount. Imagine that mount disappears one time and emby scans the library later. That issue is mentioned multiple times on the forums and is said "to be fixxed" but its not. 
It wont find any items and just deletes everything in the internal database. Plex for example just shows that the items are offline. 

Other issues are some little ones, like not tested updates which change configurations on their own or updates which keep crashing. But it was OSS and was fixxed quickly (Happened multiple times tho)

Those are my main issues, now have fun proofing me wrong.

**Comment by softworkz** [comment]
I don't want to prove you wrong. You may have valid points.
But I'm wondering a bit about your list because quite a number of the topics you're listing are not related to user experience at all.
Do you want to use Emby as your personal media server or do you want to do development?
Most of your topics are not from a user perspective.

**Comment by nvllsvm** [comment]
> Create pull requests for the public plugins. Maybe there's even room for collaboration at some time.

I encourage no one to do this as one needs to sign rights over to the Emby team via a CLA when opening a pull request. Nothing would stop them from later closing that plugin's source code.

**Comment by nvllsvm** [comment]
I have trust issues that this issue will remain public. Archived in wayback machine. https://web.archive.org/web/20181207144322/https://github.com/MediaBrowser/Emby/issues/3479

**Comment by mooninite** [comment]
Closing off the entire project because of a TV schedule feature? Insane. I was getting FREE TV schedule service through TV Guide and zap2xml. This news is extremely disappointing.

Luckily the older branch can be forked and progress can continue. I expect a new "Emby" with a new name and a new logo to be at the forefront before the year ends.

**Comment by NovaPhoenix** [comment]
Have all people who have contributed code given their consent on a license change? Because if not, distributing binaries without the source code is a violation of the GPLv2 license, last I checked.

**Comment by ryanwalder** [comment]
@NovaPhoenix The Emby team have been violating the GPL for years, doub't they'll start caring now.

**Comment by zimmertr** [comment]
Disappointing.

**Comment by tylermolamphy** [comment]
I bought a lifetime pass literally less than two weeks ago, and you pull this shit? I'm getting a refund. 

Shame on you Emby.

**Comment by sinni800** [comment]
> 
> 
> @NovaPhoenix The Emby team have been violating the GPL for years, doub't they'll start caring now.

I guess a contributer should start threatening to sue over their GPLed additions to the project. Can't really ever get that taint out unless you convince the contributor to relicense.

**Comment by LukePulverenti** [comment]
Just to prevent misinformation from spreading, all contributions within the codebase have CLA's attached that allow us to re-license. Any older contributions that predate our CLA's are no longer present in the codebase, and have not been for quite a long time. We have actually rewarded many of our past contributors by employing them for more work and will continue to do so. We are still committed to open source to the extent possible that allows us to survive as a business.
