### ISSUE TITLE
With the update to V4 - Library scan errors

### ISSUE THREAD

**Issue by IceBoosteR** [MediaBrowser/Emby#3530]
Hi everyone,

after the upgrade to version 4, no matter if it is version 4.0.0.0 or 4.0.2.0, the library scan is not doing what it should. So I do add a new movie to my server while I do not have an internet connection (due to provider issues for instance). In that case the movie will be added, but no  metadata can be pulled of course. In the past it was the case, that with the next library scan where I do have a stable internet connection, those metadata was automatically pulled - as the metadata was missing. Now with version 4 this is not working anymore. All movies will stay in my library without any metadata and I have to identify them manually to pull the metadata, and even a manual library scan is not pulling the missing metadata.

Cheers.

**Comment by LukePulverenti** [comment]
Hi, actually it has always been this way. We have never really had automatic retries. This is something I attempted to do a long time ago, like 4-5 years ago, but push back was really hard as users were constantly complaining of slow library scans due to repeated attempts to contact external metadata providers.
