### ISSUE TITLE
Identify doesn't work on a title with same name

### ISSUE THREAD

**Issue by rhazor** [MediaBrowser/Emby#3591]
E.g. when you click Identify and search by name 'Highlander' it doesn't find the Highlander series from 1992-1998

By IMDb ID tt0103442 it finds the correct poster, but on save loads the movie poster from 1986

Same by ID 4414 from TheMovieDb.

And it says 1986-1998 when the TV show is from 1992-1998. So for some reason it pulls data from the movie Highlander from 1986.

![chrome_2019-12-29_23-55-01](https://user-images.githubusercontent.com/22996586/71563352-c3ffbe80-2a96-11ea-9651-c5da38e55670.png)

**Comment by LukePulverenti** [comment]
Hi, i could be mistaken, but I don't see that series when searching tvdb:
https://www.thetvdb.com/search?menu%5Btype%5D=TV&query=highlander

If tvdb is the highest priority metadata provider for your TV library, then that's what the Identify feature will be searching with, which means this is expected behavior when searching by name.

**Comment by rhazor** [comment]
https://www.imdb.com/title/tt0103442/
https://www.themoviedb.org/tv/4414-highlander-the-series

**Comment by LukePulverenti** [comment]
I understand, did you read my comment? if you want MovieDb to be your primary metadata provider, then you'll need to configure your library that way.

**Comment by rhazor** [comment]
https://www.thetvdb.com/series/highlander but it's messed up, it contains the movie mixed in from 1986  etc.

**Comment by LukePulverenti** [comment]
> https://www.thetvdb.com/series/highlander but it's messed up, it contains the movie mixed in from 1986 etc.

If tvdb is your highest priority metadata provider for your TV library, then this is what you'll get.

**Comment by rhazor** [comment]
![chrome_2019-12-30_00-09-20](https://user-images.githubusercontent.com/22996586/71563462-a59ac280-2a98-11ea-827d-77e2a2422c1b.png)

IMDb isn't even available to choose from, but it is available when searching and identifying, what's the point what it finds from IMDb if it pulls from other providers?

![emby](https://user-images.githubusercontent.com/22996586/71563502-235ece00-2a99-11ea-9ea5-85006e3330cb.gif)

**Comment by LukePulverenti** [comment]
Imdb is not a free and open data service, that's why it's not there. The reason to allow entering Imdb Id's is because Movie Db and Tvdb both support lookup by Imdb Id.

In this case, Tvdb doesn't have that Imdb Id in their database so it returned 0 results. MovieDb does have it, so it found a match with the Identify feature. But then the normal library scanning process took over from there, and Tvdb is your highest priority metadata provider.

**Comment by rhazor** [comment]
I unticked TheTVDB and the other one and left only TheMovieDb ticked and arranged on top and it still pulls the poster from TheTVDB.

**Comment by LukePulverenti** [comment]
That's the metadata provider. Make sure to also do the for your image providers for that library.

**Comment by rhazor** [comment]
Fixed

**Comment by LukePulverenti** [comment]
Thanks for the feedback. This is a one-off case but I'm going to make a note of it and come back and review it later to see how we can make handling this situation easier.
