### ISSUE TITLE
add multiple audio language movie files

### ISSUE THREAD

**Issue by jeyca** [MediaBrowser/Emby#3606]
I sometimes have different files for the same movie with different audio languages. At the moment, they either turn up as duplicates, or I can choose a primary movie language and add the other into the extras folder.

That works, but as "extras" are shown beneath the cast/crew it is kind of hidden that there is an extra audio language. Is there no naming convention to make them available with the audio dropdown like when you have an .mkv with multiple audio channels?

**Comment by Atera** [comment]
There's already an option to have multiple versions of the same film if you have more than one file. Rather than appear in the audio drop‐down (as it's a different file with different video) there is instead a separate version drop‐down menu. You can either manually link up the files or follow the naming convention to have them autodetected. The naming can be "Title - version.ext" or "Title (year) - version.ext" where 'Title' is the name of the film and the folder, and 'version' is anything you want to use to identify it such as '4K', 'Dutch', '3D', etc.  
If you really want to share the same video but switch between audio with the audio drop‐down you'll need to remux the files in question so that a single file contains the audio streams in question.

**Comment by LukePulverenti** [comment]
Hi, yes please see our multi-version movie naming guide here:
https://support.emby.media/support/solutions/articles/44001159102-movie-naming
Thanks.
