### ISSUE TITLE
Update the 'latest' tag in the docker hub for Emby Server

### ISSUE THREAD

**Issue by Draxter** [MediaBrowser/Emby#3731]
This is very trivial, but it appears that the `latest` tag in the [Docker Hub](https://hub.docker.com/r/emby/embyserver/tags)  has not been updated in a while, and still links to an old version `4.6.7.0` of Emby.
It would be useful to get this regularly updated as many users utilise the `latest` tag to easily keep their Emby server up to date.

**Comment by LukePulverenti** [comment]
HI, 4.6.7 is the latest stable release. We're getting closer to releasing 4.7, which is currently in beta.

**Comment by Draxter** [comment]
Oh, is that how you do it? Fair enough. Could always add a ‘stable’ tag for stable releases and use ‘latest’ for the latest version. That’s how it’s usually done.

**Comment by LukePulverenti** [comment]
> Oh, is that how you do it? Fair enough. Could always add a ‘stable’ tag for stable releases and use ‘latest’ for the latest version. That’s how it’s usually done.

Hi, yes I agree that latest probably should have pointed to latest beta rather than latest stable, but at this point it would be too disruptive of a change to make to every single one of our Docker users.

If at some point we were to make other changes to our Docker container that would be equally as dramatic, then we could look at adding this change into it as well, since at that point it would probably be a fresh start for everyone. Thanks.
