### ISSUE TITLE
Bitrate reported by mediainfo is incorrect for ISOs/DVD

### ISSUE THREAD

**Issue by xnappo** [MediaBrowser/Emby#980]

**Comment by LukePulverenti** [comment]
We are getting this information from ffprobe, which doesn't natively support dvd's and iso's. It will generally be pretty accurate when the dvd has only a single VOB. When it has multiple VOB's, it might have problems. Rather than keeping this ticket open forever, we might as well just acknowledge that this is a won't fix unless dvd's start making a comeback in the market.
